# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d9f4d9a996261f60ba8539714d5a2fcf1f1947bd2b5ce2abadadcf42b32c7216e746561af476e92a6093d3838976b5b0ca24a0bac9025afcd67a35179c8ecc0

test:
  secret_key_base: eda868bea7fe0dd5330c5a64f0363dfcd45a65fab2321580c67e6849ed6714d67cda1a5362b796ef51024b1745a35a96811547e59fe24d8a95317e4e6370d24a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
